name: Build Project-Raptor

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Use Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "latest"

            - run: npm install -g npm

            - run: npm install -g pnpm

            - run: sudo apt update

            - run: sudo apt upgrade -y